# Generated by Django 4.2.16 on 2024-09-27 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="date",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="name",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="option_a",
            field=models.CharField(default="Option A", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b",
            field=models.CharField(default="Option B", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c",
            field=models.CharField(default="Option C", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d",
            field=models.CharField(default="Option D", max_length=100),
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title",
            field=models.CharField(default="Untitled Quiz", max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="courses.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="courses.course",
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
