# Generated by Django 4.2.16 on 2024-09-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_quiz_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="teacher",
        ),
    ]
